### ISSUE TITLE
Very Good !! Can i post an example ?

### ISSUE THREAD

**Issue by mikyweb** [TradeMe/bootup.js#1]
<script type="text/javascript" src="bootup.js"></script>

<script>
var arr = new Array("a.jpg","b.jpg","c.mp3");
var opt = new Object();
opt.debug = true;
new BootUp(arr, opt);
</script>

**Comment by mhuggins** [comment]
That seems like a pretty convoluted example compared to something like this:

```
new BootUp([ "a.jpg","b.jpg","c.mp3" ] , { debug: true });
```

**Comment by zeke** [comment]
The DSL looks nice and I simple, but I too would like a practical demo, ideally in the README.

**Comment by djmc** [comment]
This is a good request, so I've made a pull request adding a bunch of examples and documentation.

I'm going to close this issue, any further comments should be added to pull request #6.
